
# 
# Classify section does a basic file/object identification
# based on fields in the object
# 
# required paths are those needed to identify an object as belonging
# to a particular data_model
# 
# n3id is the field to be used for unique identification of an
# object in the data store, if empty n3 will assign a unique id.
# 
[[classifier]]
data_model = "SIF"
required_paths = ["*.RefId"]
n3id = "*.RefId"
links = ["RefId","LocalId"]

[[classifier]]
data_model = "XAPI"
required_paths = ["actor.name", "actor.mbox", "object.id", "verb.id"]
n3id = "id"
links = ["actor.mbox","actor.name","object.id","object.definition.name"]

[[classifier]]
data_model = "Syllabus"
required_paths = ["learning_area", "subject", "stage"]
n3id = "id"
links = ["learning_area", "subject", "stage"]
unique = ["subject","stage"]

[[classifier]]
data_model = "Subject"
required_paths = ["Subject.subject", "Subject.synonyms"]
n3id = "id"
links = ["Subject.learning_area", "Subject.subject", "Subject.stage", "Subject.synonyms"]
unique = ["Subject.subject","Subject.stage"]

[[classifier]]
data_model = "Lesson"
required_paths = ["Lesson.learning_area", "Lesson.lesson_id"]
n3id = "id"
links = ["Lesson.learning_area", "Lesson.subject", "Lesson.stage"]
unique = ["Lesson.subject","Lesson.stage"]




